### PR TITLE
Midterm upload

### PR DESCRIPTION
**Pull request by AdrianFilimon1707**

### CODE REVIEW

**Review by Liitle — COMMENTED** [review]
Good job, it looks good. To you want to add the context managers? Do you need help with those?

**Comment by AdrianFilimon1707** [comment]
Context managers in the Midterm Assignment ? 
Hmm? Yes I would :-)

**Comment by Liitle** [comment]
> Context managers in the Midterm Assignment ?
> Hmm? Yes I would :-)

My bad here, not context managers. I was referring to decorators. The two decorators from the assignment

**Comment by AdrianFilimon1707** [comment]
> > Context managers in the Midterm Assignment ?
> 
> > Hmm? Yes I would :-)
> 
> 
> 
> My bad here, not context managers. I was referring to decorators. The two decorators from the assignment

I will try yes, I will let you know when to look.

**Pull request merged**
